package engine

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/home-server-project/home-server-deployer/internal/model"
	"github.com/home-server-project/home-server-deployer/internal/paths"
	"github.com/home-server-project/home-server-deployer/internal/podman"
)

func (e *Engine) ExecutePlan(ctx context.Context, id string) (model.OperationResult, error) {
	p, err := e.state.GetPlan(id); if err != nil { return model.OperationResult{}, err }
	if time.Now().After(p.ExpiresAt) { return model.OperationResult{}, fmt.Errorf("plan expired") }
	if p.Digest != planDigest(p) { return model.OperationResult{}, fmt.Errorf("plan digest mismatch") }
	if len(p.Drift) > 0 { return model.OperationResult{}, fmt.Errorf("administrator drift detected; refusing %s", p.Operation) }
	if p.Operation != "install" { in,err:=e.state.GetInstance(p.InstanceID);if err!=nil{return model.OperationResult{},err};if len(e.detectDrift(ctx,in))>0{return model.OperationResult{},fmt.Errorf("administrator drift appeared after planning; refusing %s",p.Operation)} }
	switch p.Operation { case "install","update": err=e.upsert(ctx,p); case "remove": err=e.remove(ctx,p) }
	r:=model.OperationResult{PlanID:p.ID,InstanceID:p.InstanceID,Operation:p.Operation,At:time.Now().UTC()};if err!=nil{r.Status="failed";r.Message=err.Error();return r,err};r.Status="succeeded";_ = e.state.DeletePlan(p.ID);return r,nil
}
func (e *Engine) upsert(ctx context.Context,p model.Plan)error{app,_:=e.catalog.Get(p.AppID);isUpdate:=p.Operation=="update";var previous model.Instance;old:=map[string]string{};if isUpdate{var err error;previous,err=e.state.GetInstance(p.InstanceID);if err!=nil{return err};for n:=range previous.Resources{s,err:=e.podman.GetQuadlet(ctx,n);if err!=nil{return err};old[n]=s}};for _,d:=range p.Directories{if _,err:=paths.EnsureDir(e.roots[d.RootID],d.RelativePath,0750);err!=nil{return err}};installed:=[]string{};fail:=func(c error)error{if isUpdate{return e.rollbackUpdate(ctx,previous,old,installed,c)};if x:=e.rollbackInstall(ctx,installed);x!=nil{return fmt.Errorf("%v; rollback failed: %w",c,x)};return c};for _,r:=range p.Resources{if err:=e.podman.InstallQuadlet(ctx,r.Name,r.Content,podman.InstallOptions{Replace:isUpdate});err!=nil{return fail(err)};installed=append(installed,r.Name)};if err:=e.systemd.Reload(ctx);err!=nil{return fail(err)};qm,err:=e.quadletMap(ctx);if err!=nil{return fail(err)};for _,r:=range p.Resources{if !r.Start{continue};q,ok:=qm[r.Name];if !ok||q.UnitName==""{return fail(fmt.Errorf("generated unit for %s not found",r.Name))};if isUpdate{err=e.systemd.Restart(ctx,q.UnitName)}else{err=e.systemd.Start(ctx,q.UnitName)};if err!=nil{return fail(err)}};qm,err=e.quadletMap(ctx);if err!=nil{return fail(err)};resources:=map[string]model.ResourceState{};for _,r:=range p.Resources{s,err:=e.podman.GetQuadlet(ctx,r.Name);if err!=nil{return fail(err)};resources[r.Name]=model.ResourceState{Name:r.Name,UnitName:qm[r.Name].UnitName,SHA256:hash(s),Source:s}};now:=time.Now().UTC();in:=model.Instance{ID:p.InstanceID,CatalogID:p.AppID,CatalogVersion:p.CatalogVersion,Parameters:p.Parameters,Resources:resources,Directories:p.Directories,InstalledAt:now,UpdatedAt:now};if isUpdate{in.InstalledAt=previous.InstalledAt;in.History=append(previous.History,model.HistoryEntry{At:now,Operation:"update",Result:"succeeded"})}else{in.History=[]model.HistoryEntry{{At:now,Operation:"install",Result:"succeeded"}}};if err:=e.state.SaveInstance(in);err!=nil{return err};return e.docs.Write(in,app)}
func(e *Engine)rollbackInstall(ctx context.Context,n []string)error{var es []error;for i:=len(n)-1;i>=0;i--{if err:=e.podman.RemoveQuadlet(ctx,n[i],true);err!=nil{es=append(es,err)}};if err:=e.systemd.Reload(ctx);err!=nil{es=append(es,err)};return errors.Join(es...)}
func(e *Engine)rollbackUpdate(ctx context.Context,prev model.Instance,old map[string]string,attempted []string,cause error)error{var es []error;for i:=len(attempted)-1;i>=0;i--{n:=attempted[i];if _,ok:=old[n];!ok{if err:=e.podman.RemoveQuadlet(ctx,n,true);err!=nil{es=append(es,err)}}};names:=make([]string,0,len(old));for n:=range old{names=append(names,n)};sort.Strings(names);for _,n:=range names{if err:=e.podman.InstallQuadlet(ctx,n,old[n],podman.InstallOptions{Replace:true});err!=nil{es=append(es,err)}};if err:=e.systemd.Reload(ctx);err!=nil{es=append(es,err)};for _,u:=range sortedUnits(prev.Resources){if err:=e.systemd.Restart(ctx,u);err!=nil{es=append(es,err)}};if len(es)>0{return fmt.Errorf("%v; rollback failed: %w",cause,errors.Join(es...))};return cause}
func(e *Engine)remove(ctx context.Context,p model.Plan)error{in,err:=e.state.GetInstance(p.InstanceID);if err!=nil{return err};app,_:=e.catalog.Get(in.CatalogID);old:=map[string]string{};for n:=range in.Resources{s,err:=e.podman.GetQuadlet(ctx,n);if err!=nil{return err};old[n]=s};for _,u:=range sortedUnits(in.Resources){if err:=e.systemd.Stop(ctx,u);err!=nil{return err}};removed:=[]string{};rollback:=func(c error)error{x:=e.rollbackRemove(ctx,in,old,removed);if x!=nil{return fmt.Errorf("%v; rollback failed: %w",c,x)};return c};for _,n:=range sortedResourceNames(in.Resources){if err:=e.podman.RemoveQuadlet(ctx,n,false);err!=nil{return rollback(err)};removed=append(removed,n)};if err:=e.systemd.Reload(ctx);err!=nil{return rollback(err)};now:=time.Now().UTC();in.RemovedAt=&now;in.UpdatedAt=now;in.History=append(in.History,model.HistoryEntry{At:now,Operation:"remove",Result:"succeeded",Note:"application data preserved"});if err:=e.state.SaveInstance(in);err!=nil{return err};return e.docs.Write(in,app)}
func(e *Engine)rollbackRemove(ctx context.Context,in model.Instance,old map[string]string,removed []string)error{var es []error;for _,n:=range removed{if err:=e.podman.InstallQuadlet(ctx,n,old[n],podman.InstallOptions{});err!=nil{es=append(es,err)}};if err:=e.systemd.Reload(ctx);err!=nil{es=append(es,err)};for _,u:=range sortedUnits(in.Resources){if err:=e.systemd.Start(ctx,u);err!=nil{es=append(es,err)}};return errors.Join(es...)}
func(e *Engine)Status(ctx context.Context,id string)(model.InstanceStatus,error){in,err:=e.state.GetInstance(id);if err!=nil{return model.InstanceStatus{},err};qs,err:=e.podman.ListQuadlets(ctx);if err!=nil{return model.InstanceStatus{},err};cs,err:=e.podman.ListContainers(ctx);if err!=nil{return model.InstanceStatus{},err};qm:=map[string]model.Quadlet{};for _,q:=range qs{qm[q.Name]=q};cm:=map[string]model.RuntimeContainer{};for _,c:=range cs{if c.SystemdUnit!=""{cm[c.SystemdUnit]=c}};o:=model.InstanceStatus{Instance:in};for _,n:=range sortedResourceNames(in.Resources){x:=in.Resources[n];r:=model.ResourceStatus{Name:n,UnitName:x.UnitName};if q,ok:=qm[n];ok{r.QuadletStatus=q.Status;if r.UnitName==""{r.UnitName=q.UnitName}};if r.UnitName!=""{r.SystemdStatus,_=e.systemd.Status(ctx,r.UnitName);if c,ok:=cm[r.UnitName];ok{cc:=c;r.Runtime=&cc}};o.Resources=append(o.Resources,r)};return o,nil}
func(e *Engine)Lifecycle(ctx context.Context,id,action string)error{in,err:=e.state.GetInstance(id);if err!=nil{return err};if in.RemovedAt!=nil{return fmt.Errorf("instance is removed")};for _,u:=range sortedUnits(in.Resources){switch action{case"start":err=e.systemd.Start(ctx,u);case"stop":err=e.systemd.Stop(ctx,u);case"restart":err=e.systemd.Restart(ctx,u);default:return fmt.Errorf("unsupported lifecycle action")};if err!=nil{return err}};return nil}
func(e *Engine)Logs(ctx context.Context,id string,tail int)(map[string]string,error){in,err:=e.state.GetInstance(id);if err!=nil{return nil,err};units:=map[string]bool{};for _,r:=range in.Resources{units[r.UnitName]=true};cs,err:=e.podman.ListContainers(ctx);if err!=nil{return nil,err};o:=map[string]string{};for _,c:=range cs{if units[c.SystemdUnit]{s,err:=e.podman.Logs(ctx,c.ID,tail);if err!=nil{return nil,err};o[c.Name]=s}};return o,nil}
func(e *Engine)Documentation(id,name string)([]byte,error){if _,err:=e.state.GetInstance(id);err!=nil{return nil,err};return e.docs.Read(id,name)}
func(e *Engine)BackupContract(id string)(model.BackupContract,error){in,err:=e.state.GetInstance(id);if err!=nil{return model.BackupContract{},err};app,ok:=e.catalog.Get(in.CatalogID);if !ok{return model.BackupContract{},fmt.Errorf("catalog missing")};return app.Spec.Backup,nil}
func(e *Engine)quadletMap(ctx context.Context)(map[string]model.Quadlet,error){qs,err:=e.podman.ListQuadlets(ctx);if err!=nil{return nil,err};m:=map[string]model.Quadlet{};for _,q:=range qs{m[q.Name]=q};return m,nil}
func sortedResourceNames(m map[string]model.ResourceState)[]string{o:=make([]string,0,len(m));for n:=range m{o=append(o,n)};sort.Strings(o);return o}
func sortedUnits(m map[string]model.ResourceState)[]string{o:=[]string{};for _,r:=range m{if r.UnitName!=""{o=append(o,r.UnitName)}};sort.Strings(o);return o}
func planDigest(p model.Plan)string{p.Digest="";b,_:=json.Marshal(p);return hash(string(b))}
func hash(s string)string{h:=sha256.Sum256([]byte(s));return hex.EncodeToString(h[:])}
func newID()(string,error){b:=make([]byte,12);if _,err:=rand.Read(b);err!=nil{return "",err};return hex.EncodeToString(b),nil}
func safeID(s string)bool{if s==""||len(s)>63||s[0]=='-'{return false};for _,r:=range s{if !(r>='a'&&r<='z'||r>='0'&&r<='9'||r=='-'){return false}};return true}
func versionAtLeast(a,b string)bool{parse:=func(s string)([3]int,bool){var x [3]int;s=strings.SplitN(strings.TrimPrefix(s,"v"),"-",2)[0];p:=strings.Split(s,".");if len(p)<2{return x,false};for i:=0;i<len(p)&&i<3;i++{if _,e:=fmt.Sscanf(p[i],"%d",&x[i]);e!=nil{return x,false}};return x,true};x,ok:=parse(a);if !ok{return false};y,ok:=parse(b);if !ok{return false};for i:=0;i<3;i++{if x[i]!=y[i]{return x[i]>y[i]}};return true}
